name: .Build and Tests

on:
    workflow_call:
    
jobs:
  build:
    uses: ./.github/workflows/workflow-build.yml

  tests:
    needs: build
    uses: ./.github/workflows/workflow-tests.yml

  e2e-tests:
    needs: build
    uses: ./.github/workflows/workflow-e2e-tests.yml 