name: .Run Unit Tests

on:
    workflow_call:
    
jobs:
    tests:
        runs-on: ubuntu-latest
        needs: build

        steps:
        - name: Setup .NET
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: 9.0.x

        - uses: actions/download-artifact@v4
          with:
            name: buildArtifact
            path: ./src

        - name: Test
          working-directory: ./src/NodeDev.Tests
          run: dotnet test --no-build --verbosity normal