name: Run End To End Tests

on:
    workflow_call:
    
jobs:
    e2e-tests:
        runs-on: ubuntu-latest
        needs: build

        steps:
        - name: Setup .NET
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: 9.0.x

        - uses: actions/download-artifact@master
          with:
            name: buildArtifact
            path: ./src

        - name: Build Necessary for Playwright
          working-directory: ./src/NodeDev.EndToEndTests
          run: dotnet build
    
        - name: Allow run
          run: chmod -R +x ./src/NodeDev.Blazor.Server/bin

        - name: Ensure browsers are installed
          run: pwsh ./src/NodeDev.EndToEndTests/bin/Debug/net9.0/playwright.ps1 install --with-deps

        - name: Test
          env:
            HEADLESS: true
          working-directory: ./src/NodeDev.EndToEndTests
          run: dotnet test --no-build --verbosity normal
      
        - name: Upload std Artifact
          if: failure()
          uses: actions/upload-artifact@v4
          with:
            name: logServer
            path: ./src/NodeDev.Blazor.Server/logs
            retention-days: 7    